name: Artifact Management
on:
  push:
    branches: ["main"] 
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: app:latest
      - name: Save Docker image as tar
        run: docker save app:latest -o app-image.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: app-image.tar

