name: Notify Slack on Push
on:
  push:
    branches: [main]
jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Slack Notification
        uses: ./actions/slack-notification
        with:
          message: "New push to the main branch"
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

